<div style="
    background: linear-gradient(90deg, #6A5ACD, #20B2AA);
    padding: 25px 10px;
    border-radius: 12px;
    text-align: center;
    margin: 10px 0;
">
    <h1 style="
        color: white;
        font-size: 30px;
        font-family: Arial, sans-serif;
        font-weight: bold;
        margin: 0;
    ">
        E-Commerce Customer Behavior and Purchase Intention Analysis
    </h1>
</div>

### Introduction to E-Commerce Customer Behavior and Purchase Intention Analysis

E-commerce refers to buying and selling products or services through online platforms. Understanding online shopper behaviour helps businesses identify browsing patterns and factors that may influence customers to make a purchase.

The purpose of this analysis is to understand online shopper behaviour and identify key factors associated with purchase intention through clear and meaningful data visualization. This project uses Python libraries such as **Pandas, NumPy, Plotly, Matplotlib, and Seaborn** to analyse the online shoppers purchasing intention dataset.

### Data Source

The dataset used for this project is the **Online Shoppers Purchasing Intention Dataset**, obtained from the UCI Machine Learning Repository.

The dataset contains information about online shopping sessions, including page visits, browsing duration, visitor type, traffic source, and whether a purchase was made during the session.

**Dataset Link:** [Online Shoppers Purchasing Intention Dataset](https://archive.ics.uci.edu/dataset/468/online+shoppers+purchasing+intention)

### Attribute Details

The dataset contains 18 attributes describing visitors' browsing behaviour, session characteristics, and purchase outcomes. Each attribute provides information that helps analyse online shopping patterns and understand factors associated with purchase intention.

| No. | Attribute | Description |
|:---:|---|---|
| 1 | Administrative | Number of administrative pages visited during the session. |
| 2 | Administrative_Duration | Time spent on administrative pages. |
| 3 | Informational | Number of informational pages visited during the session. |
| 4 | Informational_Duration | Time spent on informational pages. |
| 5 | ProductRelated | Number of product-related pages visited during the session. |
| 6 | ProductRelated_Duration | Time spent on product-related pages. |
| 7 | BounceRates | Average bounce rate of the pages visited during the session. |
| 8 | ExitRates | Average exit rate of the pages visited during the session. |
| 9 | PageValues | Average value of pages visited before completing a transaction. |
| 10 | SpecialDay | Closeness of the visit date to a special day or occasion. |
| 11 | OperatingSystems | Operating system used by the visitor. |
| 12 | Browser | Browser used by the visitor. |
| 13 | Region | Geographic region of the visitor. |
| 14 | TrafficType | Category of traffic source that brought the visitor to the website. |
| 15 | VisitorType | Type of visitor, such as returning visitor or new visitor. |
| 16 | Month | Month in which the session occurred. |
| 17 | Weekend | Indicates whether the session occurred on a weekend. |
| 18 | Revenue | Indicates whether a purchase was completed during the session (True or False). |

### Imported Required Libraries

The following Python libraries are are imported for performing data loading,cleaning,exploration,and visualization in this project.

- **Pandas:** Used for data manipulation, cleaning, and analysis.
- **NumPy:** Used for numerical computations and array operations.
- **Matplotlib:** Used to create basic plots and charts.
- **Seaborn:** Used to create statistical visualizations.
- **Plotly Express:** Used to create interactive visualizations.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## Data Loading and Initial Overview


In this section, the dataset is loaded into a Pandas DataFrame. The initial overview helps us understand the structure, size, column names, and data types of the dataset before performing data preprocessing and analysis.

### (1) Dataset Loading

In [3]:
df=pd.read_csv("online_shoppers_intention.csv")

***info:*** The dataset is imported into a Pandas DataFrame using the `read_csv()` function. This allows us to access, inspect, and analyse the data using Python.

### (2) Initial Overview of the Dataset

In [4]:
#Viewing the Dataset
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

***info:*** The `head()` method is used to display the first five rows of the dataset. This provides an initial look at the data and helps us understand how the values are organised across different columns.

In [5]:
# Display Dataset Dimensions
df.shape

(12330, 18)

***info:*** The `shape` attribute is used to determine the total number of rows and columns in the dataset. This helps us understand the size of the dataset before proceeding with data preprocessing.

In [7]:
##Checking DataFrame Structural Summary
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  str
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  str
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), str(2)
memory usage: 1.5 MB

***Info:*** Provides a complete summary of the dataset.It displays the number of rows and columns,column names,non-null value counts,and data type of each column,as well as the memory usage of the DataFrame.Therefore it helps to identify which columns need preprocessing.

In [8]:
#Display Column Names
df.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Revenue'],
      dtype='str')

***info:*** The `columns` attribute is used to display all the column names in the dataset. This helps us identify the available attributes and refer to them correctly during data analysis and preprocessing.

In [9]:
#Checking Missing Values
df.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

***info:*** Used to find how many missing values are present in each column.

In [10]:
#Displaying Statistical Summary
df.describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType
count,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000
mean,2.315166,80.818611,0.503569,34.472398,31.731468,1194.746220,0.022191,0.043073,5.889258,0.061427,2.124006,2.357097,3.147364,4.069586
std,3.321784,176.779107,1.270156,140.749294,44.475503,1913.669288,0.048488,0.048597,18.568437,0.198917,0.911325,1.717277,2.401591,4.025169
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,184.137500,0.000000,0.014286,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000
50%,1.000000,7.500000,0.000000,0.000000,18.000000,598.936905,0.003112,0.025156,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,4.000000,93.256250,0.000000,0.000000,38.000000,1464.157214,0.016813,0.050000,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,8.000000,13.000000,9.000000,20.000000

***Info:*** Provides summary statistics for numerical columns including mean,median,standard deviation,minimum and maximum values.

In [13]:
#Checking Duplicate Records
print("Duplicate records found:",df.duplicated().sum())

Duplicate records found: 125

***info:*** The `duplicated()` method identifies duplicate rows, and the `sum()` function counts the total number of duplicate records in the dataset.
The duplicate record check identified 125 duplicate rows in the dataset.

## Data Pre-processing 


This step ensures the dataset is clean,consistent,and suitable for analysis.The cleaning steps include (1)**Handling missing values**,(2)**Removing duplicates**,(3)**Correcting Data Types**(4)**Creating Derived columns**,(5)**Filtering data**(6)**Standardizing column names and Categorical values**.

#### (1) Handling missing values

**Observation:**  The missing value check shows that all 18 columns contain zero missing values. Therefore, no missing value treatment is required for the dataset.

#### (2) Removing duplicates

In [15]:
#Removing duplicates
df.drop_duplicates(inplace=True)

In [16]:
#Verifying the removal of duplicates
print("Duplicate records found after removal:",df.duplicated().sum())

Duplicate records found after removal: 0

In [18]:
#checking the dimensions of the dataset after removing duplicates
print("Dimensions of the dataset after removing duplicates:", df.shape)

Dimensions of the dataset after removing duplicates: (12205, 18)

***info:*** The dataset was checked for duplicate entries using `df.duplicated().sum()` during the initial overview, which identified 125 duplicate rows. The `drop_duplicates()` function was applied to remove these records. After removal, the dataset was verified to ensure that no duplicate rows remained. Now the dataset contains 12,205 rows and 18 columns.

#### (3) Correcting Data Types

In [19]:
#checking the data types of each column
df.dtypes

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                          str
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                    str
Weekend                       bool
Revenue                       bool
dtype: object

***info:*** The data types of the dataset were examined. The numerical columns use integer or floating-point types, while `Month` and `VisitorType` contain strings, and `Weekend` and `Revenue` contain Boolean values. All existing data types are suitable for the intended analysis; therefore, no data type conversion was necessary.

#### (4) Creating Derived Columns

In this step, three new columns, `TotalPagesVisited`, `BrowsingActivityCategory`, and `TotalPageDuration`, are created using existing attributes. The `TotalPagesVisited` column represents the total number of administrative, informational, and product-related pages visited during a session. The `BrowsingActivityCategory` column classifies sessions into Low, Medium, and High browsing activity based on the total number of pages visited. The `TotalPageDuration` column represents the combined time spent on administrative, informational, and product-related pages. These derived columns help us understand visitors' browsing behaviour and support further analysis of purchase patterns.

In [ ]:
#Creating a new column "TotalPagesVisited" that sums up the values of "Administrative", "Informational", and "ProductRelated" columns
df["TotalPagesVisited"] = (df["Administrative"] + df["Informational"] + df["ProductRelated"])

In [23]:
# Viewing the first few rows of the selected columns
df[["Administrative", "Informational", "ProductRelated", "TotalPagesVisited"]].head(8)

   Administrative  Informational  ProductRelated  TotalPagesVisited
0               0              0               1                  1
1               0              0               2                  2
2               0              0               1                  1
3               0              0               2                  2
4               0              0              10                 10
5               0              0              19                 19
6               0              0               1                  1
7               1              0               0                  1

***info:*** A new column, `TotalPagesVisited`, was created by adding the values of `Administrative`, `Informational`, and `ProductRelated`. This derived column represents the total number of pages visited during each session and can be used to analyse visitors' browsing activity.

In [ ]:
#Before creating new column "BrowsingActivityCategory" based on the values of "TotalPagesVisited" column, checking the
#  statistical summary of "TotalPagesVisited" column to understand its distribution and determine appropriate thresholds for categorization.
df["TotalPagesVisited"].describe()

count    12205.000000
mean        34.893240
std         46.627336
min          0.000000
25%          9.000000
50%         20.000000
75%         42.000000
max        746.000000
Name: TotalPagesVisited, dtype: float64

In [35]:
#creating a new column "BrowsingActivityCategory" based on the values of "TotalPagesVisited" column
df["BrowsingActivity"] = pd.cut(df["TotalPagesVisited"], bins=[-1, 9, 42, float("inf")], labels=["Low", "Medium", "High"])

In [36]:
#Count the sessions in each category
df["BrowsingActivity"].value_counts()

BrowsingActivity
Medium    5909
Low       3290
High      3006
Name: count, dtype: int64

***info:*** The statistical summary of `TotalPagesVisited` was examined to understand the distribution of page visits.

The sessions were classified into three categories: **Low** (9 or fewer pages), **Medium** (more than 9 and up to 42 pages), and **High** (more than 42 pages). Finally, the `value_counts()`methods were used to count the sessions in each category and display the results in category order.

In [37]:
#Creating a new column "TotalPageDuration" that sums up the values of "Administrative_Duration", "Informational_Duration", and "ProductRelated_Duration" columns
df["TotalPageDuration"] = (df["Administrative_Duration"] + df["Informational_Duration"] + df["ProductRelated_Duration"])

In [38]:
#Viewing the first few rows of the selected columns
df[["Administrative_Duration", "Informational_Duration", "ProductRelated_Duration", "TotalPageDuration"]].head()

,Administrative_Duration,Informational_Duration,ProductRelated_Duration,TotalPageDuration
0,0.0,0.0,0.000000,0.000000
1,0.0,0.0,64.000000,64.000000
2,0.0,0.0,0.000000,0.000000
3,0.0,0.0,2.666667,2.666667
4,0.0,0.0,627.500000,627.500000

**Info:** A new column, `TotalPageDuration`, was created by adding the values of `Administrative_Duration`, `Informational_Duration`, and `ProductRelated_Duration` for each session. This column represents the combined time spent on these three types of pages and helps us understand visitors' browsing duration. It can also be used in further analysis to explore the relationship between browsing duration and purchase behaviour.

#### (5) Filtering Data

Filtering is the process of selecting specific rows from a dataset based on given conditions. In this step, we examine the dataset to determine whether any records need to be filtered for further analysis. Data will only be removed when there is a clear reason to do so, ensuring that useful information is preserved.


 Since all records are relevant to analysing customer browsing behaviour and purchase intention, no additional filtering was required at this stage.

#### (6) Standardizing Column Names and Categorical Values


### Standardizing Column Names:

In this step, leading and trailing spaces are removed, all column names are converted to lowercase, and underscores are added to separate words in selected column names. This creates a consistent naming convention and makes column names easier to read and use in Python.

In [40]:
#Displaying All Column Names
print("Original Column Names:",df.columns.tolist())

Original Column Names: ['Administrative', 'Administrative_Duration', 'Informational', 'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration', 'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month', 'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType', 'Weekend', 'Revenue', 'TotalPagesVisited', 'BrowsingActivity', 'TotalPageDuration']

In [ ]:
# Standardizing Column Names

df.columns = df.columns.str.strip().str.lower()

df.rename(columns={
    "productrelated": "product_related",
    "visitortype": "visitor_type",
    "operatingsystems": "operating_systems",
    "traffictype": "traffic_type",
    "totalpagesvisited": "total_pages_visited",
    "browsingactivity": "browsing_activity",
    "totalpageduration": "total_page_duration",
    "productrelated_duration": "product_related_duration",
    "bouncerates": "bounce_rates"
}, inplace=True)

In [43]:
#Displaying Updated Column Names
print("Updated Column Names:",df.columns.tolist())

Updated Column Names: ['administrative', 'administrative_duration', 'informational', 'informational_duration', 'product_related', 'productrelated_duration', 'bouncerates', 'exitrates', 'pagevalues', 'specialday', 'month', 'operating_systems', 'browser', 'region', 'traffic_type', 'visitor_type', 'weekend', 'revenue', 'total_pages_visited', 'browsing_activity', 'total_page_duration']

***Info:***  **`str.strip()`** removes leading and trailing spaces from column names to avoid hidden formatting issues. **`str.lower()`** converts all column names to lowercase to maintain a consistent naming convention. **`rename()`** is used to add underscores between words in selected column names, improving readability and making them easier to use during data analysis.

### Standardizing Categorical Values:

Categorical values represent groups or categories within a dataset. In this step, we examine the unique values in categorical columns to identify inconsistent labels or formatting that may need to be standardized.

In [44]:
# Checking Unique Categorical Values

print("Month:", df["month"].unique())
print("Visitor Type:", df["visitor_type"].unique())
print("Weekend:", df["weekend"].unique())
print("Revenue:", df["revenue"].unique())

Month: <StringArray>
['Feb', 'Mar', 'May', 'Oct', 'June', 'Jul', 'Aug', 'Nov', 'Sep', 'Dec']
Length: 10, dtype: str
Visitor Type: <StringArray>
['Returning_Visitor', 'New_Visitor', 'Other']
Length: 3, dtype: str
Weekend: [False  True]
Revenue: [False  True]

In [45]:
# Standardizing Month Values, keeping only the first three letters of the month names for consistency
df["month"] = df["month"].str[:3]

In [46]:
# viewing the unique values of the "month" column after standardization
df["month"].unique()

<StringArray>
['Feb', 'Mar', 'May', 'Oct', 'Jun', 'Jul', 'Aug', 'Nov', 'Sep', 'Dec']
Length: 10, dtype: str

***Info:*** The unique values in the categorical columns were examined to identify inconsistencies.

The `month` column contains a mixture of abbreviated and full month names. Therefore, the month values are standardized to use a consistent three-letter format.

In visitor type column, The categories `Returning_Visitor`, `New_Visitor`, and `Other` follow a consistent naming format. Therefore, no standardization was required for this column.

In the `weekend` and `revenue` columns, Both columns contain consistent Boolean values (`True` and `False`). The `weekend` column indicates whether a session occurred on a weekend, while the `revenue` column indicates whether a purchase was completed. Therefore, no standardization was required for these columns.